### ISSUE TITLE
子女端APP：點入 選單 「我的長輩」想要修正或更新或查看 結果一片空白

### ISSUE THREAD

**Issue by silvergate2022** [silver-gate/public#13]
https://user-images.githubusercontent.com/99379113/156097512-2a0a2ea0-58cc-41f6-8433-4f840186a399.mp4
![S__67108868](https://user-images.githubusercontent.com/99379113/156097532-9f0ea545-6ad2-4083-9805-0857ff45e4b1.jpg)

**Comment by chunyenHuang** [comment]
已修正 v1.0.36
