### ISSUE TITLE
後台系統增加＿餐點進價（成本）｜餐點售價

### ISSUE THREAD

**Issue by silvergate2022** [silver-gate/public#2]

**Comment by chunyenHuang** [comment]
已更新 需要麻煩手動修改與增加成本
<img width="1068" alt="Screen Shot 2022-02-11 at 12 04 24 PM" src="https://user-images.githubusercontent.com/12788155/153662238-578bd72a-48b1-4ea5-9e4d-c2315726cc70.png">
