### ISSUE TITLE
會員更新照片，沒辦法即時顯示在選單列表

### ISSUE THREAD

**Issue by silvergate2022** [silver-gate/public#4]
如下圖，我們已經有更新照片
![S__66461744](https://user-images.githubusercontent.com/99379113/153334910-d93736e3-74e3-4587-8233-1f5840f42178.jpg)
可以成功送出按鈕
![S__66461746](https://user-images.githubusercontent.com/99379113/153334926-2e98ad68-eab7-4b3e-9ffd-a9c7d269dfe2.jpg)

但是選單無變更

**Comment by chunyenHuang** [comment]
已修正
