### ISSUE TITLE
APP前端，變更按鈕說明文字：按鈕贊助長輩餐食，改成『贊助長輩服務』

### ISSUE THREAD

**Issue by silvergate2022** [silver-gate/public#5]
![S__66461748](https://user-images.githubusercontent.com/99379113/153335012-98dd85e8-392b-480d-82c2-1875d95515f3.jpg)
按鈕贊助長輩餐食，改成『贊助長輩服務』

**Comment by chunyenHuang** [comment]
![Simulator Screen Shot - iPhone 12 Pro - 2022-02-10 at 09 40 13](https://user-images.githubusercontent.com/12788155/153464946-9f212add-296b-454a-abfc-a92680aafebe.png)
