### ISSUE TITLE
app：訂單詳情頁面下方新增如欲修改訂單的註明

### ISSUE THREAD

**Issue by silvergate2022** [silver-gate/public#7]
![S__38944795](https://user-images.githubusercontent.com/99379113/153551162-01bff1ad-0fd8-4bbe-8ea5-a2482ed0f309.jpg)

訂餐完成後 在訂單詳情的頁面如果發現有誤是否可以加註：如需修改訂單請聯繫客服呢（或是超連結至官方）line？
官方line連結：https://lin.ee/8wpxrBL

**Comment by chunyenHuang** [comment]
| 訂單頁面 | 漢堡 |
| ------------- | ------------- |
| ![Simulator Screen Shot - iPhone 12 Pro - 2022-02-11 at 11 58 39](https://user-images.githubusercontent.com/12788155/153661541-88d7c4e2-4c13-4663-8f07-eaa3e2731eaf.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2022-02-11 at 11 58 42](https://user-images.githubusercontent.com/12788155/153661492-d18fc203-68f9-4715-9428-52568b4ba2bf.png) |
