### ISSUE TITLE
後台：下單後後台訂單詳情為空白連結

### ISSUE THREAD

**Issue by silvergate2022** [silver-gate/public#8]
https://user-images.githubusercontent.com/99379113/153551534-df857272-ddc3-4cdb-bf49-86735efeaa3c.mp4

**Comment by chunyenHuang** [comment]
https://app.silvergatedelivery.com/order/a06e71a0-8b06-11ec-9cab-3737b35728df

**Comment by chunyenHuang** [comment]
已修正 訂單可以正常顯示 主要問題是緊急聯絡人空白
APP部分已新增緊急聯絡人
![Simulator Screen Shot - iPhone 12 Pro - 2022-02-11 at 12 02 50](https://user-images.githubusercontent.com/12788155/153662045-3f0f0b2b-5384-4f74-a8e0-afd0f8de5288.png)
